disallowed-methods = [
    # Panicking methods
    "std::result::Result::unwrap",
    "std::result::Result::expect",
    "std::option::Option::unwrap",
    "std::option::Option::expect",
    "std::panic",
]

# Allow certain pedantic lints for practical reasons
# See: https://rust-lang.github.io/rust-clippy/master/index.html
allow = [
    "clippy::missing-errors-doc", # Tedious to document every possible error
    "clippy::missing_panics_doc", # We don't use panics
    "clippy::module_name_repetitions", # Sometimes repetition is clear
    "clippy::must_use_candidate", # Not always applicable
    "clippy::wildcard_imports", # Useful for prelude patterns
]
