# Allow a few pedantic lints for practical reasons
allowed-by-default = [
    "clippy::missing-errors-doc",
    "clippy::module-name-repetitions",
    "clippy::implicit-return",
    "clippy::must-use-candidate",
    "clippy::missing-panics-doc",
    "clippy::missing-safety-doc"
]
