[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
runner = "probe-run --chip STM32H750VBTx"

[target.aarch64-unknown-linux-gnu]
# No specific runner needed for Linux, it's a standard build target
