use slint::{Model, SharedString};
use std::rc::Rc;
use tokio::sync::mpsc;

// This will be generated by the build script
slint::include_modules!();

pub async fn ui_task(mut rx: mpsc::Receiver<crate::TelemetryFrame>) {
    // Set environment variables for DRM/KMS backend
    std::env::set_var("SLINT_BACKEND", "linuxkms");
    // This may need to be adjusted depending on the system
    std::env::set_var("SLINT_DRM_DEVICE", "/dev/dri/card0");

    let dashboard = Dashboard::new().unwrap();

    let ui_handle = dashboard.as_weak();
    tokio::spawn(async move {
        while let Some(telemetry) = rx.recv().await {
            let ui = ui_handle.upgrade().unwrap();
            ui.set_rpm(telemetry.rpm as i32);
            ui.set_map_kpa(telemetry.map_kpa as f32);
            ui.set_afr(telemetry.afr);
            ui.set_ignition_advance(telemetry.ignition_advance_deg);
        }
    });

    // Handle Ctrl+C to gracefully exit
    let (tx_term, mut rx_term) = mpsc::channel(1);
    ctrlc::set_handler(move || {
        tx_term.blocking_send(()).unwrap();
    })
    .expect("Error setting Ctrl-C handler");

    let dashboard_weak = dashboard.as_weak();
    tokio::spawn(async move {
        rx_term.recv().await;
        println!("Ctrl-C received, exiting UI.");
        if let Some(dashboard) = dashboard_weak.upgrade() {
            dashboard.hide().unwrap();
        }
    });

    dashboard.run().unwrap();
    println!("UI task finished.");
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_ui_bindings() {
        // This test can't run the UI, but we can check that the bindings exist.
        // The build script will fail if the slint file is invalid.

        // We can't create a Dashboard instance here without a backend.
        // So this is just a compile-time check.
        assert!(true);
    }
}
