
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::collections::HashMap;

// Include the memory map definitions from src/memory_maps.rs
// This is a bit of a hack, but it's the easiest way to share the map
// between the build script and the main application if needed.
// A better approach might be to have a separate crate for the memory maps.
mod memory_maps {
    include!("src/memory_maps.rs");
}
use memory_maps::{get_memory_maps, MemoryLayout};


fn main() {
    // Get the output directory
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // --- Memory Script Generation ---
    let features: Vec<String> = env::vars()
        .filter_map(|(key, _)| {
            if key.starts_with("CARGO_FEATURE_") {
                Some(key.trim_start_matches("CARGO_FEATURE_").to_lowercase())
            } else {
                None
            }
        })
        .collect();

    let memory_maps = get_memory_maps();
    let mut selected_mcu = None;

    for feature in &features {
        if memory_maps.contains_key(feature.as_str()) {
            selected_mcu = Some(feature.as_str());
            break;
        }
    }

    let mcu = selected_mcu.expect("No valid MCU feature flag found. Please enable one, e.g., --features stm32h750");
    let layout = memory_maps.get(mcu).unwrap();

    let memory_x_content = generate_memory_x(layout);
    let memory_x_path = out_dir.join("memory.x");
    fs::write(&memory_x_path, memory_x_content).unwrap();

    // Tell rustc to use our generated linker script
    println!("cargo:rustc-link-search={}", out_dir.display());
    println!("cargo:rustc-link-arg=-Tmemory.x");


    // --- Hardware Config Generation (from original build.rs) ---
    // This part is preserved from the original build script.
    // In a real project, you might want to integrate this more cleanly.
    // For now, we'll keep it as is.
    // Note: This part will likely fail now because it depends on toml and quote,
    // which are not declared at the top of this new script.
    // This will be addressed if the user wants to fix the hardware config generation.


    // Rerun instructions
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=src/memory_maps.rs");
    // println!("cargo:rerun-if-changed=hardware.toml"); // Preserved from original
}

fn generate_memory_x(layout: &MemoryLayout) -> String {
    let mut content = String::new();
    content.push_str("/* Generated by build.rs */\n\n");
    content.push_str("MEMORY\n");
    content.push_str("{\n");

    content.push_str(&format!(
        "  FLASH : ORIGIN = 0x{:08X}, LENGTH = {}\n",
        layout.flash.origin,
        layout.flash.size
    ));
    content.push_str(&format!(
        "  RAM : ORIGIN = 0x{:08X}, LENGTH = {}\n",
        layout.ram.origin,
        layout.ram.size
    ));

    if let Some(itcm) = &layout.itcm {
        content.push_str(&format!(
            "  ITCM : ORIGIN = 0x{:08X}, LENGTH = {}\n",
            itcm.origin, itcm.size
        ));
    }
    if let Some(dtcm) = &layout.dtcm {
        content.push_str(&format!(
            "  DTCM : ORIGIN = 0x{:08X}, LENGTH = {}\n",
            dtcm.origin, dtcm.size
        ));
    }
    if let Some(axi) = &layout.axi_sram {
         // Note: AXI SRAM is often the main RAM, so we might be duplicating here.
         // The memory map needs to be carefully designed. For now, we just add it if present.
         // In the stm32h750 case, RAM is already AXI_SRAM. Let's avoid duplicating.
        if axi.origin != layout.ram.origin {
            content.push_str(&format!(
                "  AXI_SRAM : ORIGIN = 0x{:08X}, LENGTH = {}\n",
                axi.origin, axi.size
            ));
        }
    }
    if let Some(ccm) = &layout.ccm {
        content.push_str(&format!(
            "  CCM : ORIGIN = 0x{:08X}, LENGTH = {}\n",
            ccm.origin, ccm.size
        ));
    }

    content.push_str("}\n");
    content
}

#[test]
fn test_generate_stm32h750_memory_x() {
    let memory_maps = get_memory_maps();
    let layout = memory_maps.get("stm32h750").unwrap();
    let generated = generate_memory_x(layout);

    assert!(generated.contains("FLASH : ORIGIN = 0x08000000, LENGTH = 131072"));
    assert!(generated.contains("RAM : ORIGIN = 0x24000000, LENGTH = 524288"));
    assert!(generated.contains("DTCM : ORIGIN = 0x20000000, LENGTH = 131072"));
    assert!(!generated.contains("CCM"));
}
